### ISSUE TITLE
Usage with Codeception

### ISSUE THREAD

**Issue by pieterbeulque** [robuust/craft-fixtures#1]
Hi, this is more of a general question than an issue with this plugin specifically.  
I'm having a hard time getting this up and running because it depends on Yii2 being enabled and for me, it all goes downhill from there. I'm not experienced with tests in PHP, so that's probably on me.

Do you by any chance have some example code or bare minimum test setup that you could share?

**Comment by boboldehampsink** [comment]
A test setup can be found here: https://github.com/robuust/craft-tests

**Comment by olets** [comment]
@boboldehampsink do you still have a public sample test setup somewhere?

**Comment by boboldehampsink** [comment]
@olets apparently it's gone, and I don't have it laying around anywhere. Sorry. But Craft has documentation on tests now: https://docs.craftcms.com/v3/testing/

**Comment by olets** [comment]
No problem thanks! Yep I've been finding the Craft repo's own tests a good resource, just interested to see how their style compares to someone else's.
